language: node_js
node_js: stable
env:
  global:
  - GH_REF: github.com/mauriciosantos/Buckets-JS.git
  - secure: QfIjKGlZ7cvDZSITpr8q72+tGdYa1uSb3HwTprM1orhNbrYSAt1+fnXppMLxeTL6mgk7VTnokMJ/WRLHgrsfqaIPQ0ic9NapDE0fId0b6whG4iCJy1iDDm0vmdiGEQeVIXd+cJ700mYuxeBgSdQvr4roBHeoXWmRH7zot0mVM/pAa/fG7gVGGJ5EC8gVmtoMBFxHBDSu+HKXRbiwBRA3un3D/tf3hs2l3frwUmy5fBllAi3fe2ruQ4uQjLIOcn/l7S2HvAIRcjLr+Nxtvz7jRZqi/fY4FuLNG8dPqR9lxIRqkYZYj5EJij1ssfiNZpMEZwfF033wxRPV6q4cdau9gw2EGtF5GUksLQXJyWzij+hox5Gfyy9oiMRI9vS9l1uiOT+x09TKsFoPRkIQG89e+JLSKLinqK4niHRpnNCJfDiENLPa50Ulf8DA9esG5SHuorh5J9zsjLc2Gm5sp8E43Oz/gskGZcSLGswjuKO/jxQ0LmKSqeQAbiB4sVN9IyeNJGZDzK5qCooy5jUmRG4MrY8cKqAvOivsvXNdvxt7q3sadb+kLGJy/AWZUg442muFEv0yOyyrSqUElriQGJ44ejKkh6SgXN8qz1mayMPPJYG9fbC7YC3/3x6iRQkxO3u+5CeoKfab8I6XqqwEcNCr3+IYlaGCnO4VPhbvvDeOgv4=
before_install: npm install -g grunt-cli
before_script: grunt test && grunt build # Test both uploaded dist and generated dist
after_success: grunt doc && .scripts/publish-docs.sh
before_deploy: git reset --hard HEAD # Clean generated files before publishing to NPM
deploy:
- provider: npm
  email: mauriciosantoss@gmail.com
  api_key:
    secure: SvFlQ0QLDPSwvfjBHs/ZoAdKsuhh2ZDdL6D62WlAshIIwJoEPubnH6U9eItzZbcW/OpD2MT75GcQVyXjY/4Q/HY+JOAonQJrsfqDTOrcBuGUk0+Ch/X669qEmXss6lmqnSfFo7dhSRgoJFot6Y9n4+WGH0B8z64J0oMQpQSJikh2DHXkSuJMjEOMZbIhH9p5YhyVXYPVQ90sPCdteL6V0F6aQfAUFS95M+sYIM9mxPfvp3b5t1if8g8Ej+cHf3oPr/hVoKp8RsM7KLTPaj+0ZjZTeR8KJ/NrtnDUyVldC6ICVD/Ves4q3bCDHmgBQCBDuqUjG6WTXJrHYSwdfiy6vP8msSewbTyx5KRlZz9373oFcAznAFW439PXXK7hvaSl/8xGb5QX00aXFXz9lQZzbgWTnx2nX44a+CWEkfIZwSRtqhfyDBjSDdUdJ/8qKisaJ+jvKHiu7EDONwo2hotepTC6u+yuQiy5v43FfrATokvR9/Q0PWQcm7pwgObPcoLijHil5ZrqTiEhOjN5lX5mh6OTgK+dU7dgjfsw5KTnr3tJ6Fiy11F0gfKrjuEW0AE1KGt/Vqv2Es9SQCsjThK4RzhDH7YvqgleBWyu1ghBmceYEOL/wJfgobr2FxNL79nTTBp2ij031BbM1lDwjXMP5Fb2C9ul0dMLxz/0o4HLFC8=
    tags: true
    repo: mauriciosantos/Buckets-JS
    all_branches: true # Bug workaround, See http://bit.ly/1YbwLuA
- provider: releases
  api_key:
    secure: cRXlKAtpDxBXf5IbkdzviQzdS9A1K8i0JgB0VSUSlIPjbaLGGUH0yqi1Jjl8zOn2uBJZmkYOMWFfR54dlXIakmoDkJadloaHdplaannOIDUwdn6LfaPqB6XGMIxe+NIZZVWLpvcjhaWnoJPnJZIUPgVS7bCx35WkGn3xCxcVjuDO4glVDrUb7ZnDAim48Pn2UJOzDEiYFuj+fsu9svV5TSC1fQEVtjG49q2VDNzuAtCWukBJKQ1jscws1q/1AeLHQgeBPXiGWUfhpRpiqaUA4pXKmfWe5/hpprOdzMi82DTPx5GuHXnw2/d/U52DEi4gfQyd3LKlKVuxkASXDgIsPpr9JMUD1KHpGTpFYOGGYs6qxBqdlal/3Sy8nCNphKRk+e4aRMdXnMDyQkFOOOlOPkuDfHjFjdKcjQj3lwez0GKbkK8j5SNEgXdoDxyv1xJkv2QGkv3+OztWp6JFb9idGJ9xjADwpX2TGHP70Focx5nnGM93azqTUU3nH7eMJdMRjoOqGopqXuXt6bub3jttmosyclF3zk5b8VpGpt3/71sNAURop/F96n3t5Yd0paoDF2TYR6z+qNRFOjzjYfoVNkaJRoY96w7WTxbcZnAQTKjooophN/Nc8/8VodKNhqE8LXmzRvHhkigxA5xXJUgj3ilQOVca0mKfpd6xRFcjW20=
  file: 
    - "dist/buckets.js"
    - "dist/buckets.min.js"
    - "dist/buckets.min.js.map"
  on:
    tags: true
    repo: mauriciosantos/Buckets-JS
	all_branches: true