language: node_js
node_js: stable
env:
  global:
  - GH_REF: github.com/mauriciosantos/Buckets-JS.git
  - secure: QfIjKGlZ7cvDZSITpr8q72+tGdYa1uSb3HwTprM1orhNbrYSAt1+fnXppMLxeTL6mgk7VTnokMJ/WRLHgrsfqaIPQ0ic9NapDE0fId0b6whG4iCJy1iDDm0vmdiGEQeVIXd+cJ700mYuxeBgSdQvr4roBHeoXWmRH7zot0mVM/pAa/fG7gVGGJ5EC8gVmtoMBFxHBDSu+HKXRbiwBRA3un3D/tf3hs2l3frwUmy5fBllAi3fe2ruQ4uQjLIOcn/l7S2HvAIRcjLr+Nxtvz7jRZqi/fY4FuLNG8dPqR9lxIRqkYZYj5EJij1ssfiNZpMEZwfF033wxRPV6q4cdau9gw2EGtF5GUksLQXJyWzij+hox5Gfyy9oiMRI9vS9l1uiOT+x09TKsFoPRkIQG89e+JLSKLinqK4niHRpnNCJfDiENLPa50Ulf8DA9esG5SHuorh5J9zsjLc2Gm5sp8E43Oz/gskGZcSLGswjuKO/jxQ0LmKSqeQAbiB4sVN9IyeNJGZDzK5qCooy5jUmRG4MrY8cKqAvOivsvXNdvxt7q3sadb+kLGJy/AWZUg442muFEv0yOyyrSqUElriQGJ44ejKkh6SgXN8qz1mayMPPJYG9fbC7YC3/3x6iRQkxO3u+5CeoKfab8I6XqqwEcNCr3+IYlaGCnO4VPhbvvDeOgv4=
before_install: npm install -g grunt-cli
before_script: grunt test && grunt build
after_success: grunt doc && .scripts/publish-docs.sh
before_deploy: git reset --hard HEAD
deploy:
- provider: npm
  email: mauriciosantoss@gmail.com
  api_key:
    secure: W9p08kc8EwsW9a9ZE0/IAvk/8fhQ9ZV2zKUuV2u77jvDMA22vWxUJbrqH3+CEdeDGreEs+O4rzY8HatKIylCLDJIg1EJ8RFYjTND90gYjITOrhA+Ko+pj8U23BkSgUqNerLu92EvQ3JBfcffYiFQipFGHhNKpjBQqxCd3sbhBTRx0lemjowV7UN3tFLs+Qy0dWPDfqh3ZDm9nwwg7aSDQjS6gNagCcV7fd9vul+0DeVCVQVWRLf1o/GHy72FqJR9OAQxG5NFEIFQOxJXYUfYiyqRrfQbXoiocIjror4ysreu39fTkqJfniZDzJUkPuHi+yVFdcFV7TT/1LumcYrOh/jSu9PtGyDbcW9o2Am+xJ44yJ4N3VBv5B2Bssnnn5xaCMfIol6p98imvbuxQx3abrTyr+ijpjkhDvUzwZ9Vb7cM4o+SYKubOIxTuyY+bNgdWiQxW/So0xMqgF8ruu7N4vej0WwNsxhaw/17htTUWwi7X6JpaSx0VtPNY0ats1dLBlDtqg5Bq6Cae9vgKPCL6NTwZZ8BzMjApLqoJrLWPb+f0QuM0qUhdfCcp4W7kw/bdpVhFR9WW9N8HkCNijqW5PG71Llwn1LS2qZQ5zPINFlXISiGk/R5ZBm3PBb4d2FyhGhVQGREPWQsKbA2+omuX+CnIkbEu0j34p8uwqXCEiE=
  on:
    tags: true
    repo: mauriciosantos/Buckets-JS
- provider: releases
  api_key:
    secure: cRXlKAtpDxBXf5IbkdzviQzdS9A1K8i0JgB0VSUSlIPjbaLGGUH0yqi1Jjl8zOn2uBJZmkYOMWFfR54dlXIakmoDkJadloaHdplaannOIDUwdn6LfaPqB6XGMIxe+NIZZVWLpvcjhaWnoJPnJZIUPgVS7bCx35WkGn3xCxcVjuDO4glVDrUb7ZnDAim48Pn2UJOzDEiYFuj+fsu9svV5TSC1fQEVtjG49q2VDNzuAtCWukBJKQ1jscws1q/1AeLHQgeBPXiGWUfhpRpiqaUA4pXKmfWe5/hpprOdzMi82DTPx5GuHXnw2/d/U52DEi4gfQyd3LKlKVuxkASXDgIsPpr9JMUD1KHpGTpFYOGGYs6qxBqdlal/3Sy8nCNphKRk+e4aRMdXnMDyQkFOOOlOPkuDfHjFjdKcjQj3lwez0GKbkK8j5SNEgXdoDxyv1xJkv2QGkv3+OztWp6JFb9idGJ9xjADwpX2TGHP70Focx5nnGM93azqTUU3nH7eMJdMRjoOqGopqXuXt6bub3jttmosyclF3zk5b8VpGpt3/71sNAURop/F96n3t5Yd0paoDF2TYR6z+qNRFOjzjYfoVNkaJRoY96w7WTxbcZnAQTKjooophN/Nc8/8VodKNhqE8LXmzRvHhkigxA5xXJUgj3ilQOVca0mKfpd6xRFcjW20=
  file: 
    - "dist/buckets.js"
    - "dist/buckets.min.js"
    - "dist/buckets.min.js.map"
  on:
    tags: true
    repo: mauriciosantos/Buckets-JS
